# Generated by Django 4.2.6 on 2024-12-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempModel',
        ),
    ]
